### ISSUE TITLE
Multi line notification. 

### ISSUE THREAD

**Issue by venkspr** [Dani3lSun/apex-plugin-toastrnotifications#3]
### Expected behavior
Created a toaster notification with new line character

### Actual behavior

The whole apex page was rendered un-readable.

### Steps to reproduce the issue

Create a new multi line notification
### APEX version (4.2.6 / 5.0.3)
5.1

### Used web server / version and platform (ORDS 3.0.3 / Tomcat 7 / Apache 2.4 / Linux x64)

Chrome

**Comment by venkspr** [comment]
![image](https://user-images.githubusercontent.com/33007860/31914137-5ffd7556-b7fe-11e7-89c0-9948afe07b09.png)

**Comment by Dani3lSun** [comment]
Hi @venkspr 

thanks for reporting that bug! Atm I´m thinking about replacing the underlying library (toastr.js) with APEX native functionality (apex.message...), thus this library is not getting updated the last 1,5 years...
I will try to fix that bug but I´m not sure when this will be...
Maybe you can use this APEX built-in functionality as well in the meantime?
https://docs.oracle.com/database/apex-5.1/AEAPI/apex-message-namespace.htm#AEAPI-GUID-D15040D1-6B1A-4267-8DF7-B645ED1FDA46

So you create a new DA with this Javascript code for a success message:
```
apex.message.showPageSuccess('Your message...');
```

or for a error message:
```
// First clear the errors
apex.message.clearErrors();
// Now show new errors
apex.message.showErrors([{
  type: "error",
  location: "page",
  message: "Page error has occurred!",
  unsafe: false
}]);
```

Benefit would be that Oracle itself maintains it and the notifications will look a bit more modern in my opinion...

**Comment by Dani3lSun** [comment]
I also added html escaping to this plugin, the issue should now be fixed with the new version! ;)
https://github.com/Dani3lSun/apex-plugin-toastrnotifications/releases/tag/v1.0.1
